AWSTemplateFormatVersion: "2010-09-09"

Description: |-
  ConfigRecorder for AWS account

Parameters:
  Product:
    Type: String
    Default: "aws"
    Description: "Product name"
  Environment:
    Type: String
    Default: "poc"
    Description: "Environment name"
  Code:
    Type: String
    Default: "000101"
    Description: "Code name"
  # DeliveryChannelDestinationBucketNameWithoutAccountId:
  #   Type: String
  #   Description: "DeliveryChannel destination bucket name without account id"
  KeyId:
    Type: String
    Description: "KMS Key ID"
  DeliveryFrequency:
    Type: String
    Default: "TwentyFour_Hours"
    Description: "Delivery frequency for Config Snapshot"
    AllowedValues:
      - "One_Hour"
      - "Three_Hours"
      - "Six_Hours"
      - "Twelve_Hours"
      - "TwentyFour_Hours"

Resources:
  ConfigurationRecorderRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "config.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Description: "Configuration Recorder Role"
      ManagedPolicyArns: 
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AWS_ConfigRole"
      # MaxSessionDuration: Integer
      ## [Replacement]
      Path: "/"
      # PermissionsBoundary: String
      # Policies: 
      #   - Policy
      ## [Replacement]
      RoleName: !Sub "${Product}-${Environment}-${Code}-configuration-recorder-role--${AWS::Region}"
      Tags: 
        - Key: "Product"
          Value: !Ref Product
        - Key: "Environment"
          Value: !Ref Environment
        - Key: "Code"
          Value: !Ref Code

  ConfigurationRecorderRolePutS3Policy:
    Type: "AWS::IAM::RolePolicy"
    Properties:
      PolicyName: !Sub "${Product}-${Environment}-${Code}-configuration-recorder-role-put-s3-policy--${AWS::Region}"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "s3:GetBucketAcl"
            Resource:
              Fn::ImportValue:
                !Sub "${Product}-${Environment}-000100-audit-bucket-arn--${AWS::AccountId}"
          - Effect: "Allow"
            Action:
              - "s3:PutObject"
            Resource:
              ## AuditBucketのconfig/*
              ## 例) arn:aws:s3:::product-environment-000100-audit-bucket-name--123456789012/config/*
              !Join 
                - ""
                - - Fn::ImportValue:
                      !Sub "${Product}-${Environment}-000100-audit-bucket-arn--${AWS::AccountId}"
                  - "/config/*"
      RoleName: !Ref "ConfigurationRecorderRole"

  ConfigurationRecorder:
    Type: "AWS::Config::ConfigurationRecorder"
    Properties:
      Name: !Sub "${Product}-${Environment}-${Code}-configuration-recorder--${AWS::Region}"
      RecordingGroup: 
        AllSupported: true
        # ExclusionByResourceTypes: 
        #   ExclusionByResourceTypes
        IncludeGlobalResourceTypes: true
        RecordingStrategy: 
          UseOnly: "ALL_SUPPORTED_RESOURCE_TYPES"
        # ResourceTypes: 
        #   - String
      RoleARN: !GetAtt ConfigurationRecorderRole.Arn

  DeliveryChannel:
    Type: "AWS::Config::DeliveryChannel"
    Properties:
      ConfigSnapshotDeliveryProperties:
        DeliveryFrequency: !Ref "DeliveryFrequency"
      ## [Replacement]
      Name: !Sub "${Product}-${Environment}-${Code}-delivery-channel--${AWS::Region}"
      S3BucketName: 
        Fn::ImportValue:
          !Sub "${Product}-${Environment}-000100-audit-bucket-name--${AWS::AccountId}"
      ## 末尾の/は不要
      S3KeyPrefix: "config/snapshot"
      S3KmsKeyArn: !Sub "arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${KeyId}"
      # SnsTopicARN: String 