AWSTemplateFormatVersion: "2010-09-09"

Description: |-
  Audit bucket for AWS account

Parameters:
  Product:
    Type: String
    Default: "aws"
    Description: "Product name"
  Environment:
    Type: String
    Default: "poc"
    Description: "Environment name"
  Code:
    Type: String
    Default: "20010"
    Description: "Code name"

Resources:
  AuditBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      # AccelerateConfiguration: 
      #   AccelerateConfiguration
      # AccessControl: String
      # AnalyticsConfigurations: 
      #   - AnalyticsConfiguration
      ## SSE-S3にて暗号化
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              # KMSMasterKeyID: String
              SSEAlgorithm: "AES256"
            # BucketKeyEnabled: Boolean
      ## [Replacement]
      BucketName: !Sub "${Product}-${Environment}-${Code}-audit-bucket--${AWS::AccountId}"
      # CorsConfiguration: 
      #   CorsConfiguration
      # IntelligentTieringConfigurations: 
      #   - IntelligentTieringConfiguration
      # InventoryConfigurations: 
      #   - InventoryConfiguration
      # LifecycleConfiguration: 
      #   LifecycleConfiguration
      LoggingConfiguration: 
        DestinationBucketName:
          Fn::ImportValue:
            !Sub "${Product}-${Environment}-000001-s3-access-log-bucket-name--${AWS::AccountId}"
        LogFilePrefix: !Sub "${Product}-${Environment}-${Code}-audit-bucket--${AWS::AccountId}"
      # MetricsConfigurations: 
      #   - MetricsConfiguration
      ## 基本的にイベントブリッジのみ有効化する
      NotificationConfiguration: 
        EventBridgeConfiguration: 
          EventBridgeEnabled: true
        # LambdaConfigurations: 
        #   - LambdaConfiguration
        # QueueConfigurations: 
        #   - QueueConfiguration
        # TopicConfigurations: 
        #   - TopicConfiguration
      # ObjectLockConfiguration: 
      #   ObjectLockConfiguration
      ## [Replacement]
      ObjectLockEnabled: false
      ## オブジェクトの所有者はバケットの所有者とする
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
      ## パブリックアクセスはすべて禁止
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      # ReplicationConfiguration: 
      #   ReplicationConfiguration
      Tags: 
        - Key: "Product"
          Value: !Ref Product
        - Key: "Environment"
          Value: !Ref Environment
        - Key: "Code"
          Value: !Ref Code
      VersioningConfiguration:
        Status: "Enabled"
      # WebsiteConfiguration: 
      #   WebsiteConfiguration

  AuditBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      ## [Replacement]
      Bucket: !Ref "AuditBucket"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AWSConfigBucketPermissionsCheck"
            Effect: "Allow"
            Principal:
              Service: "config.amazonaws.com"
            Action: "s3:GetBucketAcl"
            Resource: !Sub "arn:${AWS::Partition}:s3:::${AuditBucket}"
            Condition:
              StringEquals:
                AWS:SourceAccount: !Ref "AWS::AccountId"
          - Sid: "AWSConfigBucketExistenceCheck"
            Effect: "Allow"
            Principal:
              Service: "config.amazonaws.com"
            Action: "s3:ListBucket"
            Resource: !Sub "arn:${AWS::Partition}:s3:::${AuditBucket}"
            Condition:
              StringEquals:
                AWS:SourceAccount: !Ref "AWS::AccountId"
          - Sid: "AWSConfigBucketDelivery"
            Effect: "Allow"
            Principal:
              Service: "config.amazonaws.com"
            Action: "s3:PutObject"
            Resource: !Sub "arn:${AWS::Partition}:s3:::${AuditBucket}/*"
            Condition:
              StringEquals:
                s3:x-amz-acl: "bucket-owner-full-control"
                AWS:SourceAccount: !Ref "AWS::AccountId"
